version: 2.1
orbs:
  snyk: snyk/snyk@1.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - snyk/scan:
          token-variable: snyk 

workflows:
  example-workflow:
    jobs:
      - example-job
